[package]
name = "linker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.21", features = ["derive"] }
lazy_static = "1.4.0"
strum = "0.25.0"
strum_macros = "0.25.2"
thiserror = "1.0.44"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
semver = { version = "1.0.18", features = ["serde"] }
chrono = { version = "0.4.26" }
forge_lib = { path = "../../forge_lib" }